name: Generate Logbook

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v4
            with:
                fetch-depth: 0  # Fetch all history

        -   name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.12'

        -   name: Install dependencies
            run: |
                pip install -r requirements.txt

        -   name: Run logbook generation script
            run: python scripts/generate_logbook.py

        -   name: Convert Markdown to DOCX
            run: |
                sudo apt-get install -y pandoc
                pandoc renders/logbook.md -o renders/logbook.docx --reference-doc=config/style-reference.docx --lua-filter=scripts/pagebreak.lua

        -   name: Convert Markdown to HTML
            run: |
                pandoc renders/logbook.md -o renders/logbook.html

        -   name: Upload Logbook Artifacts
            uses: actions/upload-artifact@v4
            with:
                name: logbook
                path: |
                    renders/

        -   name: Commit and push changes
            run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git checkout -B logbook
                git add renders/
                git add markdown/
                git commit -m "chore: render logbook" || echo "No changes to commit"
                git push origin logbook --force || echo "No changes to push"
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}